version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder   # Chỉ build đến stage builder để cache nếu cần (có thể bỏ)
    volumes:
      - .:/app
    command: npm run build

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    # volumes:
    #   - ./dist/demo1:/usr/share/nginx/html
    ports:
      - "4200:80"
    depends_on:
      - app
